---
- name: 'Set sysctl variables.'
  ansible.posix.sysctl:
      ignoreerrors: true
      name: '{{ item.name }}'
      value: '{{ item.value }}'
      state: 'present'
      sysctl_set: true
      reload: true
  loop: '{{ security_sysctl_vars }}'

- name: 'Check /etc/default/grub exists.'
  ansible.builtin.stat:
      path: '/etc/default/grub'
  register: 'security_etcdefaultgrub'

- name: 'Deploy grub flags.'
  when: security_etcdefaultgrub.stat.exists
  ansible.builtin.replace:
      path: '/etc/default/grub'
      regexp: >
          ^(GRUB_CMDLINE_LINUX=(?:(?![" ]{{ item.option | regex_escape }}=).)*)(?:[" ]
          {{ item.option | regex_escape }}=\S+)?(.*")$'
      replace: '\1 {{ item.option }}={{ item.value }}\2'
      backup: true
  loop: '{{ security_grub_flags }}'
  notify:
      - 'Update grub.'
      - 'Update initramfs.'

- name: 'Use jitterentropy_rng.'
  ansible.builtin.blockinfile:
      path: '/etc/modules-load.d/jitterentropy_rng.conf'
      create: true
      mode: '644'
      block: 'jitterentropy_rng'
...
