---
- name: 'Security tasks.'
  tags:
      - 'security'
  ansible.builtin.include_tasks: '{{ item }}.yml'
  loop:
      - 'kernel'
      - 'filesystem'
      - 'priviledge_escalation'
      - 'ulimit'
      - 'auditd'
      - 'ssh'
      - 'iptables'
      - 'disable_crash_reporters'
...
